[Interface]
Address = 10.66.66.1/24
ListenPort = 45182
PrivateKey = MKVgIgsLcmKhHfgw3FumyrVbLz2etA4+wXhcvpqUU3E=
SaveConfig = false
PostUp = sysctl -w net.ipv4.ip_forward=1
PostUp = iptables -I INPUT -p udp --dport 45182 -j ACCEPT
PostUp = iptables -I FORWARD -i wg0 -j ACCEPT
PostUp = iptables -I FORWARD -o wg0 -j ACCEPT
PostDown = iptables -D INPUT -p udp --dport 45182 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -o wg0 -j ACCEPT

[Peer]
PublicKey = USfEZkXrm2+MqR/tkTR27pI3ACaTHw2zPTYDlNWaI1k=
AllowedIPs = 10.66.66.2/32
PersistentKeepalive = 25

[Peer]
PublicKey = h3vje9bga/c0LOID6d8EbWceB2akp09DMVp+q1SNoX0=
AllowedIPs = 10.66.66.3/32, 192.168.46.0/24
PersistentKeepalive = 25

[Peer]
PublicKey = 27/aU4MmHTIzcnVP4b++3jteE4rX7M3hWDvPy9cKa1M=
AllowedIPs = 10.66.66.139/32
PersistentKeepalive = 25

[Peer]
PublicKey = ODTx9mlL2tAMMCPgqKBOyu+HIeDuwXrMDUDI75J2n2c=
AllowedIPs = 10.66.66.11/32
PersistentKeepalive = 25

[Peer]
PublicKey = 41IAUv2ivGYXKm7Ul7JKqQb89D83DTge/bUySOB15n0=
AllowedIPs = 10.66.66.12/32
PersistentKeepalive = 25

[Peer]
PublicKey = faDdaQW7ipTBWEovSNr83qZChhQqn1HFRJMY4ijWSRs=
AllowedIPs = 10.66.66.13/32
PersistentKeepalive = 25

[Peer]
PublicKey = CIdW6Ysknxy5UnLOWWgVdjT/a4rrsiMjpSmyC7VGoR0=
AllowedIPs = 10.66.66.14/32
PersistentKeepalive = 25

[Peer]
PublicKey = rMNygvLBzvb9rOItprC/BzOSuhZ5Cek0FUade2nTEyo=
AllowedIPs = 10.66.66.10/32
PersistentKeepalive = 25
