services:
  agent:
    image: ${PORTAINER_AGENT_IMAGE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      resources:
        reservations:
          memory: 32M
        limits:
          memory: 128M

  portainer:
    image: ${PORTAINER_SERVER_IMAGE}
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          memory: 64M
        limits:
          memory: 256M

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
